### ISSUE TITLE
[RFE] Allow non supported hardware for testing purposes

### ISSUE THREAD

**Issue by e-minguez** [openshift/sriov-network-operator#133]
The current operator version injects udev rules to avoid NetworkManager to manage the VFs but only for a few cards.
It would be nice to have instructions on how to provide the same behaviour for unsupported NICs.
It can be as simple as applying a machine config such as:

```shell
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  creationTimestamp: null
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-etc-udev-rules-d-11-nm-unmanaged-rules
spec:
  config:
    ignition:
      config: {}
      security:
        tls: {}
      timeouts: {}
      version: 2.2.0
    networkd: {}
    passwd: {}
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,QUNUSU9OPT0iYWRkfGNoYW5nZSIsIEFUVFJTe2RldmljZX09PSIweDE1MTUiLCBFTlZ7Tk1fVU5NQU5BR0VEfT0iMSIK
          verification: {}
        filesystem: root
        group:
          name: root
        mode: 420
        path: /etc/udev/rules.d/11-nm-unmanaged.rules
        user:
          name: root
    systemd: {}
  osImageURL: ""
```

Where the udev rule is:

```shell
ACTION=="add|change", ATTRS{device}=="0x1515", ENV{NM_UNMANAGED}="1"
```

(where 0x1515 is the PCI ID)

**Comment by zshi-redhat** [comment]
We have simplified the process of adding new NIC support in operator.
It aggregates the NIC IDs in a single map which will be referred in each Opeartor managed components (including sriov config daemon which injects udev rules ): https://github.com/openshift/sriov-network-operator/blob/master/pkg/apis/sriovnetwork/v1/helper.go#L34

I think perhaps we can make the `NicIdMap` as a configurable configMap and allows adding new NIC IDs dynamically.

**Comment by andreaskaris** [comment]
I suggested: https://github.com/openshift/sriov-network-operator/pull/416

**Comment by andreaskaris** [comment]
This one can be closed.

**Comment by andreaskaris** [comment]
Just for completeness:

In order to use the feature, create a ConfigMap that looks as follows:
~~~
apiVersion: v1
data:
  X520: 8086 154d 10ed
  X540: 8086 154d 10ee
  X560: 8086 154d 10ef
kind: ConfigMap
metadata:
  name: unsupported-nic-ids
  namespace: openshift-sriov-network-operator
~~~

Each line in the ConfigMap is:
~~~
<human readable name>: <vendor ID> <pf ID> <vf ID>
~~~
