### ISSUE TITLE
Raising a meaningful error message if iommu is not enabled in bios

### ISSUE THREAD

**Issue by fedepaol** [openshift/sriov-network-operator#162]
When configuring a device to use the vfio driver, if IOMMU is not enabled in the bios of the machine, the resulting `SriovNetworkNodeState` will report a failure along the line of `write error: No such device` when trying to bind a device to the vfio driver.

My suggestion here is to check if iommu is enabled (by checking the content of /sys/class/iommu`, and provide a more descriptive error message, so that the admin can understand how to fix the error.

**Comment by fedepaol** [comment]
@zshi-redhat @pliurh does this make sense?

**Comment by zshi-redhat** [comment]
> @zshi-redhat @pliurh does this make sense?

@fedepaol Yes, I think it makes sense, this helps improve debugging experience which is our major  target in 4.5. Maybe we could do the check a little earlier in `tryEnableIommuInKernelArgs` when detecting `vfio-pci` driver is configured in policy and fail the policy config immediately.

**Comment by pliurh** [comment]
I agree.
