### ISSUE TITLE
Add manifests to master or release-4.2 branches

### ISSUE THREAD

**Issue by thiagoalessio** [openshift/sriov-network-operator#2]
I'm trying to add `sriov-network-operator` to OCP, as requested in [ART-672](https://jira.coreos.com/browse/ART-672), but the `manifests` directory is currently only present on [art](https://github.com/openshift/sriov-network-operator/tree/art) branch ... we'll need to have it in either [master](https://github.com/openshift/sriov-network-operator/tree/master) or [release-4.2](https://github.com/openshift/sriov-network-operator/tree/release-4.2). (@adammhaile might be able to explain the reasons)

Related conversation: https://github.com/openshift/ocp-build-data/pull/157#pullrequestreview-251013872

**Comment by shiywang** [comment]
cc @pliurh

**Comment by adammhaile** [comment]
Basically, we have naming standards for the branches we build from. With a very few exceptions the only branches we will build from are:
- `master`
- `openshift-master` (No, this one isn't valid to use in this case)
- `release-4.Y` where Y is the minor version in question
- `enterprise-4.Y` (old standard, no longer allowed for new repos)

We *might* temporarily allow a testing branch, but I try to avoid it if at all possible as it will need to be one of the above in the end.

**Comment by pliurh** [comment]
Just add manifests to master and release-4.2 branch, Please try again.

**Comment by thiagoalessio** [comment]
Hi @pliurh, thank you for adding the manifests there!

However I faced another problem, regarding the contents of your `operator-manifests` dir: Our CI complains about a missing file (it assumes a certain directory structure as well)
```
ERROR [containers/sriov-network-operator] sriov-network-operator: file does not exist:
/...real path omitted .../sriov-network-operator/operator-manifests/4.2/image-references
```

@adammhaile or @shiywang, please correct me if I'm wrong, but seems that `sriov-network-operator`'s manifests are incomplete.

Here are some examples of "good" manifests I could find:
* https://github.com/openshift/cluster-logging-operator/blob/master/manifests/4.2/image-references
* https://github.com/openshift/ansible-service-broker/blob/release-4.2/operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.2/image-references
* https://github.com/operator-framework/operator-metering/blob/master/manifests/deploy/openshift/olm/bundle/4.2/image-references
* https://github.com/openshift/elasticsearch-operator/blob/master/manifests/4.2/image-references

And @pliurh, sorry for letting you know about those problems incrementally, is the first time I'm performing this kind of task, so I'm literally "learning on the job" and can't yet foresee what makes our Jenkins happy.

**Comment by pliurh** [comment]
@thiagoalessio So don't be sorry. This is also the first time for me to go though this process. However I do hope we have better documentation to describe what to do in detail. In Red Hat Operators - Productization doc, I cannot find the steps which needs to be taken precisely.

Regarding to the image-references file, could you tell what image name I should use there?  Currently, there is no sriov-network-operator image built under quay.io/openshift yet.

**Comment by pliurh** [comment]
@thiagoalessio I've added the image-references file, could you try again?

**Comment by thiagoalessio** [comment]
@pliurh still failing, but now for (yet another) reason.

The `image-references` file is not considered a valid YAML because of a missing space between key/value on the last line:

https://github.com/openshift/sriov-network-operator/blob/release-4.2/manifests/4.2/image-references#L17

**Error:**
```
019-06-20 06:33:06,437 ERROR [containers/sriov-network-operator] while scanning a simple key
  in "/.../sriov-network-operator/manifests/4.2/image-references", line 17, column 7
could not find expected ':'
  in "/.../sriov-network-operator/manifests/4.2/image-references", line 18, column 1
```

Could be reproduced with a [linting](http://www.yamllint.com/) tool:

![before](https://user-images.githubusercontent.com/190616/59843932-eda69300-9359-11e9-98db-1348aca86129.png)
![after](https://user-images.githubusercontent.com/190616/59843939-f13a1a00-9359-11e9-8ab4-1ca870721aaa.png)

**That should do it:** (on `release-4.2` and `master`)

```diff
- name:quay.io/openshift/origin-sriov-network-device-plugin:4.2.0
+ name: quay.io/openshift/origin-sriov-network-device-plugin:4.2.0
```

**Comment by thiagoalessio** [comment]
@pliurh still failing, but now for (yet another) reason.

The `image-references` file is not considered a valid YAML because of a missing space between key/value on the last line:

https://github.com/openshift/sriov-network-operator/blob/release-4.2/manifests/4.2/image-references#L17

**Error:**
```
019-06-20 06:33:06,437 ERROR [containers/sriov-network-operator] while scanning a simple key
  in "/.../sriov-network-operator/manifests/4.2/image-references", line 17, column 7
could not find expected ':'
  in "/.../sriov-network-operator/manifests/4.2/image-references", line 18, column 1
```

**That should do it:** (on `release-4.2` and `master`)

```diff
- name:quay.io/openshift/origin-sriov-network-device-plugin:4.2.0
+ name: quay.io/openshift/origin-sriov-network-device-plugin:4.2.0
```

**Comment by thiagoalessio** [comment]
All good, build passing! No longer an issue 🎉
