### ISSUE TITLE
Operator is not deployed on kubernetes due to failure in deploying webhooks

### ISSUE THREAD

**Issue by Mmduh-483** [openshift/sriov-network-operator#214]
Deploying the operator fails on kubernetes, due to missing secrets, which is generated by some annotations from openshift, it generates a the dir `/etc/tls` which contain the certificate to contact with the k8s api.

Webhook:
1- https://github.com/openshift/sriov-network-operator/blob/master/bindata/manifests/webhook/001-service.yaml#L8 
2- https://github.com/openshift/sriov-network-operator/blob/master/bindata/manifests/webhook/server.yaml#L53

Operator webhook:
1- https://github.com/openshift/sriov-network-operator/blob/master/bindata/manifests/operator-webhook/001-service.yaml#L8
2- https://github.com/openshift/sriov-network-operator/blob/master/bindata/manifests/operator-webhook/server.yaml#L53

**Comment by Mmduh-483** [comment]
@moshe010 @adrianchiris @pliurh

**Comment by zshi-redhat** [comment]
@Mmduh-483  webhooks don't work in kubernetes as it is required that the openshift `cluster-authentication-operator` is running in the cluster.

To test in kubernetes, you will need to disable webhooks by exporting `export ENABLE_ADMISSION_CONTROLLER=false` environment variable. This will disable operator webhook and sriov device plugin webhook. Currently there is an [issue](https://github.com/openshift/sriov-network-operator/pull/211) with `ENABLE_ADMISSION_CONTROLLER` that it cannot be recoganized by operator. If you could build an operator image with the fix applied and export the operator image when deploying, it should be able to disable both webhooks and get the operator installed successfully.
