### ISSUE TITLE
SriovNetwork clientset is missing

### ISSUE THREAD

**Issue by ormergi** [openshift/sriov-network-operator#271]
Hello
I am trying to vendor [SriovNetwork](https://github.com/openshift/sriov-network-operator/tree/master/pkg/apis/sriovnetwork/v1) to another project in order to create `SriovNetwork` object in a cluster with go kubernetes client, 
but It is not possible because there is no clientset for `SriovNetwork`.

**Comment by zshi-redhat** [comment]
@ormergi there are only two clientset available, SriovOperatorConfig and SriovNetworkNodeState because we don't use other clientsets in this project. If there is a need for SriovNetwork, we will need to regenerate the clientset and add the missing one.

**Comment by zshi-redhat** [comment]
May I know which project you're working on?

**Comment by ormergi** [comment]
KubeVirt :)

**Comment by zshi-redhat** [comment]
> Thanks for quick response, the project is KubeVirt :)

Could you please explain a bit on how kubevirt is going to use sriovnetwork clientset?

**Comment by ormergi** [comment]
I want to use sriovnetwork clientset in order to create sriovnetwork object on a cluster in tests
