### ISSUE TITLE
Network-attachment-definition not updated after network update

### ISSUE THREAD

**Issue by oglok** [openshift/sriov-network-operator#31]
This issue appears when updating the SriovNetwork object with networkNamespace enabled. The NetworkAttachmentDefinition object should be updated accordingly, but the operator doesn't reconcile the desired state of the network with the "net-att-def".

In this case, VLAN id was updated in the network, but not in the "net-att-def".
 
```
apiVersion: v1
items:
- apiVersion: sriovnetwork.openshift.io/v1
  kind: SriovNetwork
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"sriovnetwork.openshift.io/v1","kind":"SriovNetwork","metadata":{"annotations":{},"name":"example-sriovnetwork","namespace":"sriov-network-operator"},"spec":{"ipam":"{\n  \"type\": \"host-local\",\n  \"subnet\": \"10.56.217.0/24\",\n  \"rangeStart\": \"10.56.217.10\",\n  \"rangeEnd\": \"10.56.217.11\",\n  \"routes\": [{\n    \"dst\": \"0.0.0.0/0\"\n  }],\n  \"gateway\": \"10.56.217.1\"\n}\n","networkNamespace":"default","resourceName":"intelnics","vlan":1050}}
    creationTimestamp: "2019-07-22T14:41:24Z"
    generation: 2
    name: example-sriovnetwork
    namespace: sriov-network-operator
    resourceVersion: "1822482"
    selfLink: /apis/sriovnetwork.openshift.io/v1/namespaces/sriov-network-operator/sriovnetworks/example-sriovnetwork
    uid: c755acc9-ac8e-11e9-a85c-0cc47a8eed4c
  spec:
    ipam: |
      {
        "type": "host-local",
        "subnet": "10.56.217.0/24",
        "rangeStart": "10.56.217.10",
        "rangeEnd": "10.56.217.11",
        "routes": [{
          "dst": "0.0.0.0/0"
        }],
        "gateway": "10.56.217.1"
      }
    networkNamespace: default
    resourceName: intelnics
    vlan: 2000
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

```
oc get network-attachment-definition -A -o yaml
apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      k8s.v1.cni.cncf.io/resourceName: openshift.com/intelnics
    creationTimestamp: "2019-07-22T14:41:24Z"
    generation: 1
    name: example-sriovnetwork
    namespace: default
    ownerReferences:
    - apiVersion: sriovnetwork.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: SriovNetwork
      name: example-sriovnetwork
      uid: c755acc9-ac8e-11e9-a85c-0cc47a8eed4c
    resourceVersion: "1571932"
    selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/example-sriovnetwork
    uid: c765f3e8-ac8e-11e9-a85c-0cc47a8eed4c
  spec:
    config: |
      {"cniVersion":"0.3.1","name":"sriov-net","type":"sriov",  "vlan":1050,"ipam":{"type":"host-local","subnet":"10.56.217.0/24","rangeStart":"10.56.217.10","rangeEnd":"10.56.217.11","routes":[{"dst":"0.0.0.0/0"}],"gateway":"10.56.217.1"}}
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by oglok** [comment]
Some logs on the sriov-network-operator pod:

`{"level":"error","ts":1563873496.9107687,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"sriovnetwork-controller","request":"sriov-network-operator/example-sriovnetwork","error":"network-attachment-definitions.k8s.cni.cncf.io \"example-sriovnetwork\" already exists","stacktrace":"github.com/openshift/sriov-network-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/openshift/sriov-network-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\ngithub.com/openshift/sriov-network-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/openshift/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/openshift/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/openshift/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/openshift/sriov-network-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}`

**Comment by aneeshkp** [comment]
Most likely it is because it using the default cached client. That only caches resources from the primary namespace. You need to instantiate your own client that does not go to the cache but to the cluster directly to overcome this.
Example: https://github.com/operator-framework/operator-marketplace/blob/master/pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go#L34

**Comment by oglok** [comment]
The operator should only watch the namespace "sriov-network-operator" and not the NetworkAttachmentDefinitions located in other namespaces. If the user wants to update the NetworkAttachmentDefinition object, the SriovNetwork should be updated, and not the other way around.

**Comment by pliurh** [comment]
Fixed by https://github.com/openshift/sriov-network-operator/pull/35
