### ISSUE TITLE
Operator doesn't work as expected when specifying "deviceID" selector in node policy

### ISSUE THREAD

**Issue by martinkennelly** [openshift/sriov-network-operator#310]
Hello,
**Env**
Centos 7.8
Vanilla k8 1.17
Admission controller turned off

I was deploying the operator and following the quick start guide.
When I was creating a node policy with a deviceID selector, it did not work as expected. When I set the deviceID as the targets PF deviceID, I could see the VFs being created, however sriov device plugin failed to find any devices for the resource pool.

When I remove deviceID field, everything works as expected. Is this expected behavior? 

Thank you,

Martin

**Comment by martinkennelly** [comment]
Config Map when I do not define deviceID selector:
{"resourceList":[{"resourceName":"intelx700xx","selectors":{"vendors":["8086"],"drivers":["iavf","mlx5_core","i40evf","ixgbevf"],"IsRdma":false},"SelectorObj":null}]}

Config Map when I utilize deviceID selector:
{"resourceList":[{"resourceName":"intelx700","selectors":{"vendors":["8086"],"devices":[""],"drivers":["iavf","mlx5_core","i40evf","ixgbevf"],"IsRdma":false},"SelectorObj":null}]}

**Comment by zshi-redhat** [comment]
> SR-IOV DP Config Map when I do not define deviceID selector:
> {"resourceList":[{"resourceName":"intelx700xx","selectors":{"vendors":["8086"],"drivers":["iavf","mlx5_core","i40evf","ixgbevf"],"IsRdma":false},"SelectorObj":null}]}
> 
> SR-IOV DP Config Map when I utilize deviceID selector:
> {"resourceList":[{"resourceName":"intelx700","selectors":{"vendors":["8086"],"devices":[""],"drivers":["iavf","mlx5_core","i40evf","ixgbevf"],"IsRdma":false},"SelectorObj":null}]}

@martinkennelly hi, I think this is the expected behavior when using unsupported device IDs.

The reason is Operator generates config map for sriov device plugin using a PF to VF device ID map, when the device ID is not in the supported list, the generated config map will contain an empty string of VF device ID. which result in the device plugin filter out all the devices it detects.

The proper way to test unsupported device ID is:
1) disable operator webhook (as you have done on k8s)
2) not use unsupported PF device ID in the sriov network node policy.

**Comment by zshi-redhat** [comment]
> > SR-IOV DP Config Map when I do not define deviceID selector:
> > {"resourceList":[{"resourceName":"intelx700xx","selectors":{"vendors":["8086"],"drivers":["iavf","mlx5_core","i40evf","ixgbevf"],"IsRdma":false},"SelectorObj":null}]}
> > SR-IOV DP Config Map when I utilize deviceID selector:
> > {"resourceList":[{"resourceName":"intelx700","selectors":{"vendors":["8086"],"devices":[""],"drivers":["iavf","mlx5_core","i40evf","ixgbevf"],"IsRdma":false},"SelectorObj":null}]}
> 
> @martinkennelly hi, I think this is the expected behavior when using unsupported device IDs.
> 
> The reason is Operator generates config map for sriov device plugin using a PF to VF device ID map, when the device ID is not in the supported list, the generated config map will contain an empty string of VF device ID. which result in the device plugin filter out all the devices it detects.
> 
> The proper way to test unsupported device ID is:
> 
>     1. disable operator webhook (as you have done on k8s)
> 
>     2. not specify unsupported PF device ID in the sriov network node policy.

btw, the supported device IDs can be found at: https://docs.openshift.com/container-platform/4.4/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov

**Comment by martinkennelly** [comment]
Thank you. This is clear to me. I will close this issue now.
