### ISSUE TITLE
There is no indication that sriov-operator is ready to use

### ISSUE THREAD

**Issue by ormergi** [openshift/sriov-network-operator#339]
I am trying to automate sriov-operator deployment and I realized there is no indication that the operator is ready to use after deployment, webhooks certificate rotation or after creating `SriovNetworkNodePolicy`.
For example: during webhooks certificate rotation or creating `SriovNetworkNodePolicy` the sriov-operator pods are up and ready but there is `NoSchedule` taint on cluster nodes.
 
To verify sriov-opearator is ready after deployment we constantly check that all pods under `kube-system` and `sriov-network-operator` namespaces conditions are `Ready=true`

Post certificate rotation for validation and mutation webhooks https://github.com/kubevirt/kubevirtci/blob/master/cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh#L214:
- Create certificate and patch caBundle for the webhooks
- Wait for taint `NoSchedue` to present. 
- Wait for taint `NoSchedue` absence.
- Verify `kube-system` and `sriov-network-operator` are up and ready

Post `SriovNetworkNodePolicy` creation https://github.com/kubevirt/kubevirtci/blob/master/cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh#L247:
- Create SriovNetworkNodePolicy 
- Wait for sriov-cni and `sriov-device-plugin` pods Ready condition to be true
- Wait for taint `NoSchedue` to present 
- Wait for taint `NoSchedue` absence. 
I noticed that on intel card (X710) if there were VF's already configured on the host, sriov-operator will restart that node configuring VF's again. 
so it is necessary to catch that taint when the node is restarted.
- Verify `kube-system` and `sriov-network-operator` are up and ready

It would be great if we have `Ready` conditions under sriov-operator `Status` to indicate what I described,
or a single condition to indicate that the sriov-operator is ready to use (create sriovNetworks)

**Comment by zshi-redhat** [comment]
> I am trying to automate sriov-operator deployment and I realized there is no indication that the operator is ready to use after deployment, webhooks certificate rotation or after creating `SriovNetworkNodePolicy`.
> For example: during webhooks certificate rotation or creating `SriovNetworkNodePolicy` the sriov-operator pods are up and ready but there is `NoSchedule` taint on cluster nodes.

What is this `NoSchedule` taint? Is it that sriov component cannot be scheduled on certain cluster nodes?

> 
> To verify sriov-opearator is ready after deployment we constantly check that all pods under `kube-system` and `sriov-network-operator` namespaces conditions are `Ready=true`

One idea is to extend current `SriovOperatorConfig` to support `Status` , have Operator detect the readiness of pods/certification and update the `SriovOperatorConfig` `Status` field.

> 
> Post certificate rotation for validation and mutation webhooks https://github.com/kubevirt/kubevirtci/blob/master/cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh#L214:
> 
>     * Create certificate and patch caBundle for the webhooks
> 
>     * Wait for taint `NoSchedue` to present.
> 
>     * Wait for taint `NoSchedue` absence.
> 
>     * Verify `kube-system` and `sriov-network-operator` are up and ready
> 
> 
> Post `SriovNetworkNodePolicy` creation https://github.com/kubevirt/kubevirtci/blob/master/cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh#L247:
> 
>     * Create SriovNetworkNodePolicy
> 
>     * Wait for sriov-cni and `sriov-device-plugin` pods Ready condition to be true
> 
>     * Wait for taint `NoSchedue` to present
> 
>     * Wait for taint `NoSchedue` absence.
>       I noticed that on intel card (X710) if there were VF's already configured on the host, sriov-operator will restart that node configuring VF's again.
>       so it is necessary to catch that taint when the node is restarted.
> 
>     * Verify `kube-system` and `sriov-network-operator` are up and ready
> 

Each node will have a `SriovNetworkNodeState` custom resource, which contains a `syncStatus` field, it can be used to say if a policy has been applied successfully or not. The `syncStatus` supports three states: succeeded, failed, inProgress. 

> 
> It would be great if we have `Ready` conditions under sriov-operator `Status` to indicate what I described,
> or a single condition to indicate that the sriov-operator is ready to use (create sriovNetworks)

**Comment by ormergi** [comment]
Hi thanks for responding :) 

> What is this `NoSchedule` taint? Is it that sriov component cannot be scheduled on certain cluster nodes?

If this taint presents on a node you cannot schedule any workload to that node, from what I saw this taint could be presented after a node has been restarted.

> One idea is to extend current `SriovOperatorConfig` to support `Status` , have Operator detect the readiness of pods/certification and update the `SriovOperatorConfig` `Status` field.
> 
This is great idea!
Is it planed for next release?

> Each node will have a `SriovNetworkNodeState` custom resource, which contains a `syncStatus` field, it can be used to say if a policy has been applied successfully or not. The `syncStatus` supports three states: succeeded, failed, inProgress.
> 
Thanks for the heads up.
I forgot to mention, I am verifying that `SriovNetworkNodePolicy` applied successfully by checking that cluster nodes has sriov VF's allocatable resource https://github.com/kubevirt/kubevirtci/blob/master/cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh#L330
Is that how `syncStatus` determined `succeeded` in the background?

**Comment by zshi-redhat** [comment]
> Hi thanks for responding :)
> 
> > What is this `NoSchedule` taint? Is it that sriov component cannot be scheduled on certain cluster nodes?
> 
> If this taint presents on a node you cannot schedule any workload to that node, from what I saw this taint could be presented after a node has been restarted.

Ok, this taint might be added by the draining library, where sriov config daemon trigger the node draining when applying a policy and uncordon the node after finishing.

> 
> > One idea is to extend current `SriovOperatorConfig` to support `Status` , have Operator detect the readiness of pods/certification and update the `SriovOperatorConfig` `Status` field.
> 
> This is great idea!
> Is it planned for next release?

This is not planned. we will need to evaluate if this is something we can do in 4.7 if no other higher priority tasks.

> 
> > Each node will have a `SriovNetworkNodeState` custom resource, which contains a `syncStatus` field, it can be used to say if a policy has been applied successfully or not. The `syncStatus` supports three states: succeeded, failed, inProgress.
> 
> Thanks for the heads up.
> I forgot to mention, I am verifying that `SriovNetworkNodePolicy` applied successfully by checking that cluster nodes has sriov VF's allocatable resource https://github.com/kubevirt/kubevirtci/blob/master/cluster-up/cluster/kind-k8s-sriov-1.17.0/config_sriov.sh#L330
> Is that how `syncStatus` determined `succeeded` in the background?

Operator doesn't check explicitly the resource name/count in node status, it just guarantees all the configuration steps(provision VFs, start device plugin pod, start cni pod etc) are done successfully without returning an error message.

We will have a task in next release to provide tooling for debugging, which might be helpful in your case. Which functions will be in that debugging tool have not been thoroughly discussed yet.
