### ISSUE TITLE
Sriov CNI bin is not in /opt/cni/bin/

### ISSUE THREAD

**Issue by fedepaol** [openshift/sriov-network-operator#34]
From what I can see (https://github.com/openshift/sriov-network-operator/blob/fe39dddcf763467e96bb86fb7a33b030cbbba798/bindata/manifests/plugins/sriov-cni.yaml#L41), the sriov cni plugin ends up in `/var/lib/cni/bin/sriov` while multus normally expects to find it in `/opt/cni/bin/` .

Is this for a particular reason? Am I missing something?
Thanks a lot in advance

**Comment by zshi-redhat** [comment]
Thanks for reporting the issue!
Yes, reason is that OpenShift uses `/var/lib/cni/bin` path to find cni binary, `multus`, `openshift-sdn` and other cni binaries are copied to the same path on OpenShift.

**Comment by fedepaol** [comment]
Closed by https://github.com/openshift/sriov-network-operator/pull/47
