### ISSUE TITLE
SRIOV-CNI failed to load netconf

### ISSUE THREAD

**Issue by rupang790** [openshift/sriov-network-operator#340]
I tried to use SR-IOV on OKD 4.5 GA version.
Installation and execution of SR-IOV Plug-in was succeed and I wrote the yaml for SR-IOV network as below.
(Use NIC which is SR-IOV Feature available, but not supported on OpenShift officially.)

<img width="335" alt="image" src="https://user-images.githubusercontent.com/40801176/92670545-3aa3ca00-f34f-11ea-94df-c4e30b86b42c.png">
<img width="228" alt="image" src="https://user-images.githubusercontent.com/40801176/92670676-7ccd0b80-f34f-11ea-8818-8be35c4d530a.png">

After that, attach the SR-IOV to sample Pod but error occurred as below:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/40801176/92670786-b69e1200-f34f-11ea-928e-c534d7d21b63.png">

I do not understand why It try to get VF information from other NIC which is not I configured.

- Configured NIC : 0000:04:00.0
- Try to get from : 0000:05:00.1
 

Also one more thing is that I could not see "intel.com/intel-nics" when I execute command below:
$ kubectl get no -o json | jq -r '[.items[] | {name:.metadata.name, allocable:.status.allocatable}]'

![image](https://user-images.githubusercontent.com/40801176/92671032-3f1cb280-f350-11ea-8878-b5dbebfbef8e.png)

Do anyone have experience about this?

**Comment by zshi-redhat** [comment]
> 
> I do not understand why It try to get VF information from other NIC which is not I configured.
> 
>     * Configured NIC : 0000:04:00.0
> 
>     * Try to get from : 0000:05:00.1
> 

`0000:04:00.0` is the PF pci address.
The error message is from sriov-cni, it tries to get the PF interface name from `0000:05:00.1` device.
This `0000:05:00.1` pci address should come from kubelet which allocates the available VF device and eventually pass it down to sriov-cni. Since you have problem detecting the VF device/resource in kubelet (as indicated in below picture that there is no available resource reported in node status), I suggest first figuring out why the resource is not exposed to kubelet.

> 
> Also one more thing is that I could not see "intel.com/intel-nics" when I execute command below:
> $ kubectl get no -o json | jq -r '[.items[] | {name:.metadata.name, allocable:.status.allocatable}]'
> 
> ![image](https://user-images.githubusercontent.com/40801176/92671032-3f1cb280-f350-11ea-8878-b5dbebfbef8e.png)
> 
> Do anyone have experience about this?

Could it be that VF is not even created on that worker node? could you check the VF device on the worker node?

**Comment by rupang790** [comment]
Thanks for quick answer.
On the worker node, the 2 VFs were created as:
![image](https://user-images.githubusercontent.com/40801176/92672799-7beaa880-f354-11ea-9d55-9fd80604fe56.png)

It seems something wrong during vf provisioning as you mentioned.

Actually, the way I deploy sriov-network-operator was clone from this git and build manually, not followed official document. (Because it does not work on my cluster)
Could this be reasons why error occurred?

**Comment by zshi-redhat** [comment]
could you share the output of `oc get configmap -n openshift-sriov-network-operator device-plugin-config -o yaml`?
the namespace might be `sriov-network-operator` if you deployed the operator on vanilla k8s environment.

Also could you check which PF this device `0000:05:00.1` belongs to?

**Comment by rupang790** [comment]
Here is the output of `oc get configmap -n openshift-sriov-network-operator device-plugin-config -o yaml`.
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/40801176/92694144-95561980-f381-11ea-8773-bd67c3435308.png">

The device `0000:05:00.1` is Physical Interface(PF), not a VF.

**Comment by zshi-redhat** [comment]
> Here is the output of `oc get configmap -n openshift-sriov-network-operator device-plugin-config -o yaml`.
> 
> The device `0000:05:00.1` is Physical Interface(PF), not a VF.

Ok, I think the issue is with above device plugin config map, it groups all the devices with same vendor IDs (8086) as a resource pool. so when you create a pod requesting device from that pool, it randomly chooses one (which happened to be the PF interface `0000:05:00.1`), then sriov-cni failed to find PF name of that PF interface because sriov-cni only supports attaching VF device to pod.

You could try specify the `pfNames` in the sriov network node policy with the pf name of `0000:04:00.0` device. 
Once the policy is successfully applied and the resource number if refreshed in node status, then re-creating the pod shall work as expected.

**Comment by rupang790** [comment]
I added `pfName` parameter on policy yaml file and re-create pod, then it successfully executed well.
Thank you for help.

However, I also test to attach the SRIOV on `KubeVirt` vmi. But it seems not work on `KubeVirt`.
Is there something more that I have to configured for `KubeVirt`?
The error case as:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/40801176/92835782-a13feb00-f416-11ea-883b-9ece967bcf7c.png">

KubeVirt yaml file as:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/40801176/92835850-b9b00580-f416-11ea-9cb9-82acb7ae00e7.png">

**Comment by zshi-redhat** [comment]
> I added `pfName` parameter on policy yaml file and re-create pod, then it successfully executed well.
> Thank you for help.
> 
> However, I also test to attach the SRIOV on `KubeVirt` vmi. But it seems not work on `KubeVirt`.
> Is there something more that I have to configure for `KubeVirt`?
> 
> The error case as:
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/40801176/92835782-a13feb00-f416-11ea-883b-9ece967bcf7c.png">
> 
> KubeVirt yaml file as:
> <img alt="image" width="266" src="https://user-images.githubusercontent.com/40801176/92835850-b9b00580-f416-11ea-9cb9-82acb7ae00e7.png">

Comparing with what I tested, one difference is in the [interfaces](https://github.com/redhat-nfvpe/openshift-baremetal-ci/blob/master/tests/kubevirt/vmi/vm-perf.yaml#L35) section: where I was using sriov, while above template uses bridge, not sure if that matters.

**Comment by SchSeba** [comment]
Hi @rupang790 please take a look on the kubevirt sriov documentation https://kubevirt.io/user-guide/#/creation/interfaces-and-networks?id=sriov

**Comment by oshoval** [comment]
> Ok, I think the issue is with above device plugin config map, it groups all the devices with same vendor IDs (8086) as a resource pool. so when you create a pod requesting device from that pool, it randomly chooses one (which happened to be the PF interface `0000:05:00.1`), then sriov-cni failed to find PF name of that PF interface because sriov-cni only supports attaching VF device to pod.

Hi,
Hope its fine that i ask the following question in this issue, if not please let me know and i will open a new one.

I see the same error 
```
  Warning  FailedCreatePodSandBox  86s                 kubelet, sriov2-worker  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "a7e4119f10decd80305af9b3b15ba8622bc8c9a4f73eb0d3b5405260d8576e32": Multus: [kubevirt-test-default1/virt-launcher-testvmiz2jls67h7qnt4ctcp64bpvt6hv7v5cmh4qm8s6v9dw]: error adding container to network "sriov": delegateAdd: error invoking DelegateAdd - "sriov": error in getting result from AddNetwork: SRIOV-CNI failed to load netconf: LoadConf(): failed to get VF information: "lstat /sys/bus/pci/devices/0000:65:11.0/physfn/net: no such file or directory"
```
But only after i create the 2nd cluster, having both clusters running in the same time.

Each of the clusters uses a different PF, which can be seen on the configmap `device-plugin-config`,
but when i create the 2nd cluster, just the 2nd cluster works fine (creating pods with nics),
but the 1st cluster which did work previously fine, stopped with this error.

According your comment, it looks like both of the clusters use the same pool maybe?
(both clusters use the same `docker network` in case its an issue)

Thanks
