### ISSUE TITLE
Failed to apply default image tag "quay.io/openshift/origin-sriov-network-operator@": couldn't parse image reference "quay.io/openshift/origin-sriov-network-operator@": invalid reference format

### ISSUE THREAD

**Issue by ptrnull** [openshift/sriov-network-operator#342]
If skopeo is not installed on the system the build succeed but the image name is incorrect and can't be pulled:

$ make deploy-setup                                                                                                                                                                                      
hack/env.sh: line 1: skopeo: command not found                                                                                                                                                                                                
hack/env.sh: line 3: skopeo: command not found                                                                                                                                                                                                
hack/env.sh: line 5: skopeo: command not found                                                                                                                                                                                                
hack/env.sh: line 7: skopeo: command not found                                                                                                                                                                                                
hack/env.sh: line 9: skopeo: command not found                                                                                                                                                                                                
hack/env.sh: line 11: skopeo: command not found                                            
hack/env.sh: line 13: skopeo: command not found                                                                                                                                                                                               
~/go/src/github.com/openshift/sriov-network-operator/deploy ~/go/src/github.com/openshift/sriov-network-operator                                                                                                                             
namespace/openshift-sriov-network-operator created           
...

$ oc get events
LAST SEEN   TYPE      REASON              OBJECT                                         MESSAGE
<unknown>   Normal    Scheduled           pod/sriov-network-operator-77cbd797b6-9hkhw    Successfully assigned openshift-sriov-network-operator/sriov-network-operator-77cbd797b6-9hkhw to master-0.clus1.t5g.lab.eng.bos.redhat.com
4m12s       Warning   InspectFailed       pod/sriov-network-operator-77cbd797b6-9hkhw    Failed to apply default image tag "quay.io/openshift/origin-sriov-network-operator@": couldn't parse image reference "quay.io/openshift/origin-sriov-network-operator@": invalid reference format
7m31s       Warning   Failed              pod/sriov-network-operator-77cbd797b6-9hkhw    Error: InvalidImageName
9m25s       Normal    SuccessfulCreate    replicaset/sriov-network-operator-77cbd797b6   Created pod: sriov-network-operator-77cbd797b6-9hkhw
9m25s       Normal    ScalingReplicaSet   deployment/sriov-network-operator              Scaled up replica set sriov-network-operator-77cbd797b6 to 1

hack/env.sh
...
export SRIOV_NETWORK_OPERATOR_IMAGE=${SRIOV_NETWORK_OPERATOR_IMAGE:-quay.io/openshift/origin-sriov-network-operator@${OPERATOR_IMAGE_DIGEST}}

I guess is the same for the rest of the images on the env.sh file.

**Comment by zshi-redhat** [comment]
@ptrnull thanks for reporting the issue!
Yes, currently local deployment relies on skopeo to retrieve image digest, I think we probably can fix it by failing the deployment explicitly if skopeo is not installed.

**Comment by ptrnull** [comment]
That would be a possible solution, yes. Do you want me to submit a PR?

**Comment by zshi-redhat** [comment]
> That would be a possible solution, yes. Do you want me to submit a PR?

Sure.
Note: for PR to be merged in openshift repos, it has to be linked to a bugzilla, otherwise we will wait until master is open to next release.

**Comment by ptrnull** [comment]
Bug created, is there a place to assign it to this issue?
https://bugzilla.redhat.com/show_bug.cgi?id=1878677

**Comment by zshi-redhat** [comment]
> Bug created, is there a place to assign it to this issue?
> https://bugzilla.redhat.com/show_bug.cgi?id=1878677

@ptrnull when you create a PR for this issue, you can link that PR to both this issue and above bugzilla.

link PR to this issue by adding `Fixes #342` in the commit message
link PR to bugzilla by adding `Bug 1878677` in the beginning of PR title.
