### ISSUE TITLE
Please prepare bundle for OCP 4.7

### ISSUE THREAD

**Issue by Ximinhan** [openshift/sriov-network-operator#371]
Now that we are fully branched for 4.7, please prepare your operator to supply a 4.7 bundle, so that 4.7 operator publishing works and doesn't overwrite 4.6 bundles. This means at least updating the package.yaml under
https://github.com/openshift/sriov-network-operator/tree/master/manifests

Reference: openshift/ocp-build-data#708

**Comment by zshi-redhat** [comment]
This issue was addressed by https://github.com/openshift/sriov-network-operator/pull/373
