### ISSUE TITLE
Request: Allow developers to use unsupported SRIOV NICs without disabling the webhook

### ISSUE THREAD

**Issue by oshoval** [openshift/sriov-network-operator#417]
Since the following commit
https://github.com/openshift/sriov-network-operator/commit/c3132b22e3fe7ca884337d6cd5c718b94091aa1a#diff-8fd5d83d7413d77ee2eab8e5c1a2ea1623d63e2aec69017a95811db9ad9edf52R70

Clusters that have unsupported SRIOV NICs are required to disable the webhook as documented in the Note here:
https://github.com/openshift/sriov-network-operator/blob/master/doc/quickstart.md

We would need please, if possible,  a method that would allow us to run the sriov-network-operator with unsupported SRIOV  NIC, but without disabling the webhook.
Since the webhook validates several parameters, we prefer to keep it.

Thanks

**Comment by zshi-redhat** [comment]
@oshoval I think this issue will be addressed by https://github.com/openshift/sriov-network-operator/pull/416

**Comment by oshoval** [comment]
Thanks @zshi-redhat 
Following

**Comment by oshoval** [comment]
Thanks closing
