### ISSUE TITLE
Issue with unsupported NICs such as the X557 which share the same VF device ID as supported cards

### ISSUE THREAD

**Issue by andreaskaris** [openshift/sriov-network-operator#448]
In https://github.com/openshift/sriov-network-operator/issues/133, I added support for unsupported NIC models. It turns out that a few unsupported models such as the X557 share the same VF 154c device ID. 

The following configmap for the Intel X557 is never annotated and webhook validation fails:

apiVersion: v1
data:
  X557: 8086 1589 154c
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"X557":"8086 1589 154c"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"unsupported-nic-ids","namespace":"sriov-network-operator"}}
  creationTimestamp: "2020-12-17T08:00:20Z"
  name: unsupported-nic-ids
  namespace: sriov-network-operator
  resourceVersion: "1949"
  selfLink: /api/v1/namespaces/sriov-network-operator/configmaps/unsupported-nic-ids
  uid: 79857698-2fce-4d05-bcad-2493bd66d80e

https://github.com/openshift/sriov-network-operator/blob/c58d32a8079f5d6f5aa0fd73b83678263f1dbca5/api/v1/helper.go#L39

We write only the VF code into the configmap for the udevrule, and only annotate the configmap if the udev rule on disk changes. Given that VF device code 154c already exists, the 2 strings are identical and the operator does not annotate the configmap. That part was made to avoid that we always rewrite the udev rule and also to avoid that we constantly rewrite the configmap.

On the other hand, the supported vendor model function checks the vendor ID and the PF ID:
https://github.com/openshift/sriov-network-operator/blob/0d8ff3eaa0848fe54440344b5a500129f068105e/pkg/webhook/validate.go#L288
~~~
	// check the vendor/device ID to make sure only devices in supported list are allowed.
	if sriovnetworkv1.IsSupportedModel(iface.Vendor, iface.DeviceID) {
		return true
	}
~~~

The implicit assumption was that there is a unique VF vendor ID per vendor ID / PF device ID combination - and that's not the case.

As a solution, at the moment, the easiest that I see is to add a comment to the udev file, listing all devices which are supported, and making sure that the file content is identical.

Another thing to ask ourselves ... is it possible to have vendor = a , pf = b, vf = c  and vendor = a, pf =b and vf = d? In that case, we might have an issue with the logic of the IsSupportedModel at that location and might rather check for IsSupportedVF or something like that.

- Andreas

**Comment by zshi-redhat** [comment]
@andreaskaris if this is an issue, shall we keep it open?

**Comment by andreaskaris** [comment]
@zshi-redhat  The person who found if will re-report it and possibly push a fix :-)

**Comment by zshi-redhat** [comment]
> @zshi-redhat The person who found if will re-report it and possibly push a fix :-)

Great, thanks!

btw, just FYI, we have mirrored an upstream repo for sriov operator at: https://github.com/k8snetworkplumbingwg/sriov-network-operator, any future issues or PRs will go to upstream project first, then be backported to this openshift repo.
