### ISSUE TITLE
Network config daemon crashing with Mellanox ConnectX4LX

### ISSUE THREAD

**Issue by fedepaol** [openshift/sriov-network-operator#48]
This seems related to https://github.com/openshift/sriov-network-operator/issues/43 but the error message is slightly different.

I am trying to setup our kubevirt CI to use the sriov operator instead of setting up manually. The tests run using a kind cluster but I don't think this is relevant since the output of the mstconfig tool is the same on the bare metal host.

I am testing with a mellanox ConnectX4LX card: 
```
mstconfig -d 0000:05:00.1 q 

Device #1:
----------

Device type:    ConnectX4LX     
Name:           N/A             
Description:    N/A             
Device:         0000:05:00.1 
```

Which do not happen to have the LINK_TYPE properties nor LINK_TYPE_P1:
```
[root@zeus08 kubevirt]# mstconfig -d 0000:05:00.1 q | grep LINK
         KEEP_ETH_LINK_UP_P1                 True(1)         
         KEEP_IB_LINK_UP_P1                  False(0)        
         KEEP_LINK_UP_ON_BOOT_P1             False(0)        
         KEEP_LINK_UP_ON_STANDBY_P1          False(0)        
         KEEP_ETH_LINK_UP_P2                 True(1)         
         KEEP_IB_LINK_UP_P2                  False(0)        
         KEEP_LINK_UP_ON_BOOT_P2             False(0)        
         KEEP_LINK_UP_ON_STANDBY_P2          False(0) 
```

This is causing the `sriov-network-config-daemon` to crash because `isSinglePortNic` [is returning an error](https://github.com/openshift/sriov-network-operator/blob/master/pkg/plugins/mellanox/mellanox_plugin.go#L271) .

config daemon logs:
```
I0731 16:50:14.687456    6475 writer.go:107] setNodeStateStatus(): syncStatus: InProgress, lastSyncError: 
E0731 16:50:14.744306    6475 mellanox_plugin.go:163] mellanox-plugin mstconfigReadData(): failed : exit status 3 : 
Device #1:
----------

Device type:    ConnectX4LX     
Name:           N/A             
Description:    N/A             
Device:         0000:05:00.0    

Configurations:                              Next Boot
-E- Unknown Parameter: LINK_TYPE
I0731 16:50:14.744344    6475 mellanox_plugin.go:157] mellanox-plugin mstconfigReadData(): try to read [LINK_TYPE_P2] for device 0000:05:00.0
I0731 16:50:14.744363    6475 mellanox_plugin.go:169] mellanox-plugin runCommand(): mstconfig [-d 0000:05:00.0 q LINK_TYPE_P2]
E0731 16:50:14.819727    6475 mellanox_plugin.go:163] mellanox-plugin mstconfigReadData(): failed : exit status 3 : 
Device #1:
----------

Device type:    ConnectX4LX     
Name:           N/A             
Description:    N/A             
Device:         0000:05:00.0    

Configurations:                              Next Boot
-E- The Device doesn't support LINK_TYPE_P2 parameter
E0731 16:50:14.819765    6475 daemon.go:147] nodeStateAddHandler(): plugin mellanox_plugin error: exit status 3
I0731 16:50:14.819810    6475 daemon.go:240] nodeStateChangeHandler(): Interface not changed
```

**Comment by moshe010** [comment]
yes, we are aware of this issue per comments on this PR https://github.com/openshift/sriov-network-operator/pull/36. We are working on fixing it.

**Comment by fedepaol** [comment]
Ok thanks, I ran a search only through issues.
Let me know if I can provide any needful information.

**Comment by fedepaol** [comment]
Also, in my case I don't have LINK_TYPE and not even LINK_TYPE_P1 / LINK_TYPE_P2 (see the grep result above) which is slightly different from what was discussed on https://github.com/openshift/sriov-network-operator/pull/36

**Comment by moshe010** [comment]
understood, we will include that also in the fix we are working on

**Comment by Mmduh-483** [comment]
@fedepaol Can you try #52 ?

**Comment by fedepaol** [comment]
Done. Still not working
Here are the logs:

```
I0805 09:21:01.760470   16134 mellanox_plugin.go:162] mellanox-plugin mstconfigReadData(): %s
Device #1:
----------

Device type:    ConnectX4LX     
Name:           N/A             
Description:    N/A             
Device:         0000:05:00.0    

Configurations:                              Default         Current         Next Boot
-E- Unknown Parameter: LINK_TYPE
I0805 09:21:01.760516   16134 mellanox_plugin.go:157] mellanox-plugin mstconfigReadData(): try to read [LINK_TYPE_P2] for device 0000:05:00.0
I0805 09:21:01.760543   16134 mellanox_plugin.go:167] mellanox-plugin runCommand(): mstconfig [-e -d 0000:05:00.0 q LINK_TYPE_P2]
I0805 09:21:01.836606   16134 mellanox_plugin.go:162] mellanox-plugin mstconfigReadData(): %s
Device #1:
----------

Device type:    ConnectX4LX     
Name:           N/A             
Description:    N/A             
Device:         0000:05:00.0    

Configurations:                              Default         Current         Next Boot
-E- The Device doesn't support LINK_TYPE_P2 parameter
E0805 09:21:01.836643   16134 mellanox_plugin.go:184] mellanox-plugin getMlnxNicFwData(): exit status 3
E0805 09:21:01.836671   16134 daemon.go:147] nodeStateAddHandler(): plugin mellanox_plugin error: exit status 3
I0805 09:21:01.836707   16134 daemon.go:240] nodeStateChangeHandler(): Interface not changed
W0805 09:21:01.836723   16134 daemon.go:115] Got an error: exit status 3
E0805 09:21:01.836754   16134 start.go:105] failed to run daemon: exit status 3
```

Please bear in mind that when I do `mstconfig q` on my device no `LINK_TYPE_P2` nor `LINK_TYPE` property appear:

```
[root@zeus08 kubevirt]# mstconfig -d 0000:05:00.1 q | grep LINK
         KEEP_ETH_LINK_UP_P1                 True(1)         
         KEEP_IB_LINK_UP_P1                  False(0)        
         KEEP_LINK_UP_ON_BOOT_P1             False(0)        
         KEEP_LINK_UP_ON_STANDBY_P1          False(0)        
         KEEP_ETH_LINK_UP_P2                 True(1)         
         KEEP_IB_LINK_UP_P2                  False(0)        
         KEEP_LINK_UP_ON_BOOT_P2             False(0)        
         KEEP_LINK_UP_ON_STANDBY_P2          False(0) 
```

**Comment by moshe010** [comment]
@fedepaol , are you sure you are on the latest PR of https://github.com/openshift/sriov-network-operator/pull/52. We change mstconfig to read all the attribute once with see 
I0805 08:34:22.718600   15968 mellanox_plugin.go:165] mellanox-plugin runCommand(): mstconfig [-e -d 0000:02:00.1 q]
I0805 08:34:22.718666   15968 mellanox_plugin.go:172] mellanox-plugin: runCommand(): mstconfig, [-e -d 0000:02:00.1 q]
I0805 08:34:27.722428   15968 mellanox_plugin.go:174] mellanox-plugin: runCommand(): 
Device #1:
----------

Device type:    ConnectX5       
Name:           MCX556A-ECA_Ax  
Description:    ConnectX-5 VPI adapter card; EDR IB (100Gb/s) and 100GbE; dual-port QSFP28; PCIe3.0 x16; tall bracket; ROHS R6
Device:         0000:02:00.1    

Configurations:                              Default         Current         Next Boot
         MEMIC_BAR_SIZE                      0               0               0               
         MEMIC_SIZE_LIMIT                    _256KB(1)       _256KB(1)       _256KB(1)       
         HOST_CHAINING_MODE                  DISABLED(0)     DISABLED(0)     DISABLED(0)

**Comment by moshe010** [comment]
@fedepaol, I mean it doesn't seem from the logs you are running the latest change in https://github.com/openshift/sriov-network-operator/pull/52. Also keep in mind that this PR is not merged yet.

**Comment by fedepaol** [comment]
I am pretty sure I have the right sources locally, but now I am afraid I am not doing the right steps.

My checkout is 
```
[root@zeus08 sriov-network-operator]# git branch
* (HEAD detached at mellanox/fix-mlnx-bug)
```

where mellanox points at @Mmduh-483 's repo. Then I run `make build` and `make run`.
Is that correct?

**Comment by Mmduh-483** [comment]
The changes are in the config daemon image, you need to build a new image
`docker build  -f Dockerfile.sriov-network-config-daemon -t <new-image> .`
Change the image name in line 44 in deploy/operator.yaml
```
            - name: OPERATOR_NAME
              value: sriov-network-operator
            - name: SRIOV_NETWORK_CONFIG_DAEMON_IMAGE
              value: <new-image>
            - name: RESOURCE_PREFIX
              value: openshift.io
```

**Comment by fedepaol** [comment]
Ok thanks. Will get back with the test result.

**Comment by fedepaol** [comment]
Seems much better:

```
0805 12:46:13.641710   26063 writer.go:107] setNodeStateStatus(): syncStatus: InProgress, lastSyncError:
I0805 12:46:16.853668   26063 mellanox_plugin.go:174] mellanox-plugin: runCommand():
Device #1:
----------

Device type:    ConnectX4LX
Name:           N/A
Description:    N/A
Device:         0000:05:00.1

Configurations:                              Default         Current         Next Boot
         MEMIC_BAR_SIZE                      0               0               0
         MEMIC_SIZE_LIMIT                    _256KB(1)       _256KB(1)       _256KB(1)
         ROCE_NEXT_PROTOCOL                  254             254             254
         NON_PREFETCHABLE_PF_BAR             False(0)        False(0)        False(0)
*        NUM_OF_VFS                          8               127             127
         SRIOV_EN                            True(1)         True(1)         True(1)
         PF_LOG_BAR_SIZE                     5               5               5
         VF_LOG_BAR_SIZE                     0               0               0

[...]
The '*' shows parameters with next value different from default/current value.
I0805 12:46:16.853730   26063 mellanox_plugin.go:241] mellanox-plugin parseMstconfigOutput(): Attributes [NUM_OF_VFS SRIOV_EN LINK_TYPE_P2]
I0805 12:46:16.853886   26063 mellanox_plugin.go:208] mellanox-plugin mlnxNicFromMap() map[NUM_OF_VFS:127 SRIOV_EN:True(1)], false
W0805 12:46:16.853922   26063 mellanox_plugin.go:233] mellanox-plugin getMlnxNicFwData(): LINK_TYPE_P* attribute was not found
I0805 12:46:16.853932   26063 mellanox_plugin.go:208] mellanox-plugin mlnxNicFromMap() map[NUM_OF_VFS:127 SRIOV_EN:True(1)], false
W0805 12:46:16.853945   26063 mellanox_plugin.go:233] mellanox-plugin getMlnxNicFwData(): LINK_TYPE_P* attribute was not found
I0805 12:46:16.853959   26063 mellanox_plugin.go:115] mellanox-plugin needDrain true needReboot true
I0805 12:46:16.853983   26063 generic_plugin.go:81] generic-plugin OnNodeStateChange()
I0805 12:46:16.854008   26063 generic_plugin.go:165] generic-plugin tryEnableIommuInKernelArgs()
I0805 12:46:16.863240   26063 generic_plugin.go:180] generic-plugin tryEnableIommuInKernelArgs(): need to reboot node
I0805 12:46:16.863299   26063 daemon.go:260] nodeStateChangeHandler(): reqDrain true, reqReboot true
I0805 12:46:16.863323   26063 daemon.go:263] nodeStateChangeHandler(): drain node
I0805 12:46:16.863334   26063 daemon.go:384] drainNode(): Update prepared; beginning drain
I0805 12:46:43.641926   26063 writer.go:57] Run(): period refresh
I0805 12:46:43.641959   26063 writer.go:67] pollNicStatus()
I0805 12:46:43.641968   26063 utils.go:35] DiscoverSriovDevices
```

I think the reboot is required because I have 4 vfs instead of 127 in my policy.
Another question: is the reboot really required in this case?

**Comment by moshe010** [comment]
so any change in the Number of VF will change the FW number of VF. So even if you have had 127 and now you request 4 it will reconfig the FW.  The reason for doing is that the more VF in NIC FW require more memory on the host. is the reboot working for you?

**Comment by fedepaol** [comment]
Pardon my ignorance. How this is different from echoing the number of needed vfs into sriov_numvfs ?

Re: reboot I have two concerns. The main one is described here https://github.com/openshift/sriov-network-operator/issues/51 , the second one is more trivial. 
We intend to use the operator to run on our CI, and since we are using kind what really happens is that the reboot involves the node of the Prow cluster.

**Comment by moshe010** [comment]
This is FW config specify the total number of VF. So more VFs more memory is needs even if you didn't create the VF in the kernel(like pre allocation). Also otherwise I could  increase the number of VF in the FW NIC and never decrease it. 
   
So issue https://github.com/openshift/sriov-network-operator/issues/51 should be fixed. 
regarding CI - I assume you can preconfigure the card to 16 VFs and aways request 16 VF right? so it won't trigger reboot.

**Comment by fedepaol** [comment]
That's clear now :-) Thanks for taking the time to explain this.

**Comment by moshe010** [comment]
sure np :)
