### ISSUE TITLE
Unsupported NIC configmap backport request to 4.6

### ISSUE THREAD

**Issue by dciancio** [openshift/sriov-network-operator#493]
I have a use-case where my customer is running OCP 4.6 and has Intel X710 NIC model (1572) which is not supported by the operator in that release.

I came across this issue:   https://github.com/openshift/sriov-network-operator/issues/133
This PR proposes the configmap :  https://github.com/openshift/sriov-network-operator/pull/416

But, the commit was included in the following branches:
```
$ git branch -r --contains 13a8fe0bb3c6da6ecd2450e137bdc44405e37427
  origin/HEAD -> origin/master
  origin/master
  origin/release-4.7
  origin/release-4.8
  origin/release-4.9

```
Would it be possible to backport this to the 4.6 version of the operator ?

**Comment by zshi-redhat** [comment]
@dciancio Thanks for creating the issue!
"1572" PF device ID is added in release-4.7, would it be possible for customer to try using 4.7 release?
We don't usually backport features to a release branch, the 1572 is not supported with 4.6 even it can be used. 

For testing purpose, maybe you could try disable operator-webhook, not guarantee it would work, but that would allow the policy be created.

**Comment by dciancio** [comment]
@zshi-redhat  In fact, the workaround you mentioned, disabling the operator webhook, is what I proposed to the customer.  I realize that the NIC model is unsupported in 4.6, but, the point was to allow for an easier way for customers to test using unsupported devices since it is not easy for them just upgrade to 4.7.  Also, upgrades from 4.6 to 4.7 are still blocked at the moment.

**Comment by zshi-redhat** [comment]
backport 1572 device ID in 4.6: https://bugzilla.redhat.com/show_bug.cgi?id=1951864
