### ISSUE TITLE
sriov-operator crashloopbackoff on Kubernetes Cluster

### ISSUE THREAD

**Issue by rupang790** [openshift/sriov-network-operator#503]
Following https://github.com/openshift/sriov-network-operator/blob/master/doc/quickstart.md, I tried to install operator on Kubernetes Cluster. According to QuickStart.md guide, webhook is disabled as default when installed on Kubernetes cluster. But it shows logs as below:
![image](https://user-images.githubusercontent.com/40801176/117904822-097bff00-b30d-11eb-8f88-fd1449cc4bb5.png)

I deployed operator as ``` make deploy-setup-k8s```. Is it bug or did I miss something?

**Comment by zshi-redhat** [comment]
Could you check if there are legacy webhooks in your environment?

`kubectl get mutatingwebhookconfiguration | grep -i sriov`
`kubectl get validatingwebhookconfiguration | grep -i sriov`

If yes, delete them and try re-deploying the operator.

**Comment by rupang790** [comment]
@zshi-redhat 
I found them as:
```
$ kubectl get mutatingwebhookconfiguration | grep -i sriov
sriov-operator-webhook-config       1          113m
$ kubectl get validatingwebhookconfiguration | grep -i sriov
sriov-operator-webhook-config            1          113m
```

So I deleted them and re-deploy ```make deploy-setup-k8s```, I keep seeing operator-webhooks. 
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/40801176/117911562-f96a1c80-b318-11eb-9f2c-d894c3525125.png">

And network-resources-injector logs show below:
![image](https://user-images.githubusercontent.com/40801176/117911641-1bfc3580-b319-11eb-9dda-b3420d5ed066.png)

**Comment by pliurh** [comment]
@rupang790 Please go to https://github.com/k8snetworkplumbingwg/sriov-network-operator and test with the upstream build.

This is repo is the downstream repo, which only for Openshift.

**Comment by rupang790** [comment]
@pliurh Thanks for comment. I will check the upstream as you said.
