### ISSUE TITLE
No synchronization between nodes in case of reboot

### ISSUE THREAD

**Issue by fedepaol** [openshift/sriov-network-operator#51]
In case the change of the NetworkNodePolicy trigger a reboot of the node (i.e. to add the needed kernel parameters, or to re-set a mellanox card), the reboot of the node is immediate.

This risks to jeopardize a zone if the same policy is applied at the same time to all the nodes. 
The reboot should be gradual and involve a small group of nodes at the same time, while keeping the zone functioning.

**Comment by pliurh** [comment]
I haven't test this scenario in a large scale cluster myself. Here is the design logic.

Before rebooting, node would be drained. Only if all pods get evicted successfully, node can reboot. If there's no available capacity in cluster, pod eviction will fail. So node shall not reboot all at the same time.

**Comment by fedepaol** [comment]
I saw the drain happening before, but I don't see checking if it fails and avoiding the reboot (but I might be missing something).

The code should be around here:
https://github.com/openshift/sriov-network-operator/blob/212dfea945e8ebe857d3b14d44edd43d4233093f/pkg/daemon/daemon.go#L265
but no error is returned there.

**Comment by pliurh** [comment]
There is a back-off mechanism in function drainNode(). It will keep on retry, until node is drained. Currently this function is implemented by MCO team. And, there is a proposal in upstream https://github.com/kubernetes/enhancements/pull/1080. We will switch to the native API, when it gets ready.

**Comment by fedepaol** [comment]
I saw that but I did not notice how long was the waiting time.
Guess this answers my question, thanks for the explanation.
