### ISSUE TITLE
vendor/device 8086/1528 is not supported

### ISSUE THREAD

**Issue by silenceper** [openshift/sriov-network-operator#552]
Error from server (vendor/device 8086/1528 is not supported): error when creating "SriovNetworkNodePolicy.yaml": admission webhook "operator-webhook.sriovnetwork.openshift.io" denied the request: vendor/device 8086/1528 is not supported

**Comment by zshi-redhat** [comment]
> Error from server (vendor/device 8086/1528 is not supported): error when creating "SriovNetworkNodePolicy.yaml": admission webhook "operator-webhook.sriovnetwork.openshift.io" denied the request: vendor/device 8086/1528 is not supported

It is not in the supported nic list : https://github.com/openshift/sriov-network-operator/blob/master/deploy/configmap.yaml
You can disable operator-webhook to workaround this issue or submit a PR to add the support for that device.

**Comment by silenceper** [comment]
Do I just need to add support in the configmap?

**Comment by silenceper** [comment]
The problem has been solved by adding the corresponding model in configmap
