### ISSUE TITLE
webhook references an incorrect annotation

### ISSUE THREAD

**Issue by weishiuchang** [openshift/sriov-network-operator#602]
While troubleshooting why my pods are not being modified by the sriov-network-operator webhooks, I noticed my mutatingwebhookconfiguration "network-resource-injector-config" does not actually have a caBundle injected by the cert-manager.

I am running on on-prem kubernetes cluster deployed via kubeadm and installing the sriov-network-operator helm chart with enableAdmissionController=true and cert-manager installed.

Following the Quick Start instructions to create self-signed certificates, I notice that line 97 https://github.com/openshift/sriov-network-operator/blob/2bfa00ead503c4f372f435f32d75460288588bc7/doc/quickstart.md?plain=1#L97 creates "network-resource-injector-service" Certificate CRD, whereas the operator is asking for "network-resource-injector-secret" https://github.com/openshift/sriov-network-operator/blob/2bfa00ead503c4f372f435f32d75460288588bc7/bindata/manifests/webhook/003-webhook.yaml#L10

According to cert-manager documentation, if the SRIOV Operator really wanted the Secret, then it should be using "inject-ca-from-secret:

```
annotations:
  cert-manager.io/inject-ca-from-secret: {{.Namespace}}/network-resources-injector-secret
```

Otherwise the current annotation key of "cert-manager.io/inject-ca-from" should use the CRD name instead:

```
annotations:
  cert-manager.io/inject-ca-from: {{.Namespace}}/network-resources-injector-service
```

Ref: https://cert-manager.io/docs/concepts/ca-injector/#injecting-ca-data-from-a-certificate-resource

**Comment by weishiuchang** [comment]
I've put in an issue with the upstream repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/217

**Comment by SchSeba** [comment]
@weishiuchang closing this issue here lets continue on the u/s repo as the sriov-operator under openshift use a different method to generate the caBundle
