### ISSUE TITLE
Can not work well with Intel x710

### ISSUE THREAD

**Issue by pengbinbin1** [openshift/sriov-network-operator#741]
I have deploy the sriov-network-operator on my cluster, but it can not wrok well with my Intel X710 NIC. The sriov-config-daemon's log like below,any one can help,thanks
![image](https://user-images.githubusercontent.com/28950491/208373754-e69e1f43-9d29-43e3-a29a-16c07653659e.png)

**Comment by SchSeba** [comment]
Hi @pengbinbin1 I can see the vfs exist.
what is the problem?
btw can you please share the config-daemon and the sriovnetworknodestate for the relevant node
Thanks!

**Comment by pengbinbin1** [comment]
> Hi @pengbinbin1 I can see the vfs exist. what is the problem? btw can you please share the config-daemon and the sriovnetworknodestate for the relevant node Thanks!

Yes，the vfs exist，but the node can not recognize them. The deviceplugin err log like below 
![Uploading image.png…]()

**Comment by pengbinbin1** [comment]
> Hi @pengbinbin1 I can see the vfs exist. what is the problem? btw can you please share the config-daemon and the sriovnetworknodestate for the relevant node Thanks!
Yes，the vfs exist，but the node can not recognize them. The deviceplugin err log like below 
![image](https://user-images.githubusercontent.com/28950491/208406531-653f7d0a-3b89-469b-88e8-2d652b7cc32d.png)

**Comment by pengbinbin1** [comment]
The sriovnetworknodestate like below
![image](https://user-images.githubusercontent.com/28950491/208406774-6148b908-1369-42f9-ba10-90ad386b2fe2.png)

**Comment by pengbinbin1** [comment]
The config-daemon err log
![image](https://user-images.githubusercontent.com/28950491/208407264-c0ea0867-e4a1-433f-a724-beaa5dea8e79.png)

**Comment by SchSeba** [comment]
Hi @pengbinbin1 this just point out that the daemon is not able to read the driver for the nic.

sounds like there is a problem with the driver for this VFs

**Comment by pengbinbin1** [comment]
Yes， it is a problem on my VF driver,thank you.

> Hi @pengbinbin1 this just point out that the daemon is not able to read the driver for the nic.
> 
> sounds like there is a problem with the driver for this VFs
Yes， it is a problem on my VF driver,thank you.
