### ISSUE TITLE
sriovnetworknodestates is not detecting sriov VF's 

### ISSUE THREAD

**Issue by HalaharviPedda** [openshift/sriov-network-operator#747]
I have deployed the "Sriov network operator" , but SriovNetworkNodeState is not showing sriov VF's in status.

==========================================
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodeState
metadata:
  creationTimestamp: "2023-01-19T14:44:35Z"
  generation: 1
  name: worker-application-pool-ko8hpyvm-eccd-ci-os-ibd-13-jenkins
  namespace: sriov-network-operator
  ownerReferences:
  - apiVersion: sriovnetwork.openshift.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: SriovNetworkNodePolicy
    name: default
    uid: fae98143-11ea-4c3d-99f7-0e6d0e89923c
  resourceVersion: "34366"
  uid: f8a29607-6d86-4322-a9f4-741bd7ca1151
spec:
  dpConfigVersion: "33771"
status:
  syncStatus: Succeeded
$
=====================================

The server has the following vf's 

$:~> sudo lshw -c network -businfo
Bus info          Device      Class          Description
========================================================
pci@0000:00:03.0              network        Virtio network device
virtio@0          eth0        network        Ethernet interface
pci@0000:00:04.0              network        Virtio network device
virtio@1          eth1        network        Ethernet interface
pci@0000:00:06.0              network        Ethernet Virtual Function 700 Series
pci@0000:00:07.0              network        Ethernet Virtual Function 700 Series
$:~>

======================================================

Node also has resources .

Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                         Requests      Limits
  --------                         --------      ------
  cpu                              1245m (65%)   2650m (139%)
  memory                           1207Mi (43%)  4618Mi (165%)
  ephemeral-storage                0 (0%)        0 (0%)
  hugepages-1Gi                    0 (0%)        0 (0%)
  hugepages-2Mi                    0 (0%)        0 (0%)
  **intel.com/intel_sriov_netdevice  2             2**

**Comment by SchSeba** [comment]
can you please check the sriov-config-daemon on that node to check the status?

**Comment by HalaharviPedda** [comment]
> can you please check the sriov-config-daemon on that node to check the status?

Thanks for the response. The sriov-config-daemon status is Running only ,

sriov-network-operator   sriov-network-config-daemon-7j5dp                                 3/3     Running             0               21h
sriov-network-operator   sriov-network-config-daemon-b88fb                                 3/3     Running             0               21h
sriov-network-operator   sriov-network-config-daemon-k2czt                                 3/3     Running             0               21h
sriov-network-operator   sriov-network-config-daemon-xfwtv                                 3/3     Running             0               21h
sriov-network-operator   sriov-network-operator-6578686c4c-4dx7h                           1/1     Running             0               21h
$:~>

config0daemon reports the below error.
I0206 06:27:45.006677 3408672 writer.go:71] RunOnce(): first poll for nic status
W0206 06:27:45.059242 3408672 utils_virtual.go:301] DiscoverSriovDevicesVirtual(): unable to find device in devicesInfo list for pci 0000:00:03.0
W0206 06:27:45.059270 3408672 utils_virtual.go:301] DiscoverSriovDevicesVirtual(): unable to find device in devicesInfo list for pci 0000:00:04.0
W0206 06:27:45.059277 3408672 utils_virtual.go:301] DiscoverSriovDevicesVirtual(): unable to find device in devicesInfo list for pci 0000:00:06.0
W0206 06:27:45.059284 3408672 utils_virtual.go:301] DiscoverSriovDevicesVirtual(): unable to find device in devicesInfo list for pci 0000:00:07.0
I0206 06:27:45.075688 3408672 writer.go:173] setNodeStateStatus(): syncStatus: , lastSyncError:

**Comment by SchSeba** [comment]
oh this is inside a virtual env right?
