### ISSUE TITLE
How to configure the same policy for different nics configurations of different nodes

### ISSUE THREAD

**Issue by dafu-wu** [openshift/sriov-network-operator#863]
Hi All:
If I have two types of nodes but the device names are inconsistent. For example, the nics of one type of node are eth1, eth2, eth3, and eth4, while the available nics of another type of node are eth2, eth4, eth6, and eth8. 
In this case, my SriovNetworkNodePolicy should How to configure? 
hope to get your help.

**Comment by zeeke** [comment]
Hi @dafu-wu! This repository is for openshift changes only.
Please, open an issue on the upstream repo https://github.com/k8snetworkplumbingwg/sriov-network-operator and discuss the issue with the rest of the community.

**Comment by dafu-wu** [comment]
> Hi @dafu-wu! This repository is for openshift changes only. Please, open an issue on the upstream repo https://github.com/k8snetworkplumbingwg/sriov-network-operator and discuss the issue with the rest of the community.

got it, thank you.
