### ISSUE TITLE
master and release-4.16 still point to 4.15 versions

### ISSUE THREAD

**Issue by mlguerrero12** [openshift/sriov-network-operator#879]
@zeeke, any plans to automate what you did in https://github.com/openshift/sriov-network-operator/pull/840?

**Comment by SchSeba** [comment]
Hi @mlguerrero12 there is already a PR for that by @liornoy

**Comment by mlguerrero12** [comment]
@liornoy did something for metallb to automatically create prs to bump version. Perhaps, we could do something similar.

**Comment by liornoy** [comment]
Yes, the [bump_metallb.yaml](https://github.com/metallb/metallb-operator/blob/main/.github/workflows/bump_metallb.yml) workflow we've implemented runs twice a day to fetch the latest Metallb. If there's a newer commit, it automatically executes scripts to update the manifests and files a pull request that includes informative details about both the old and new commits.

**Comment by zeeke** [comment]
AFAIK, `openshift/*` repositories do not run github actions. BTW, if you have any good idea, feel free to open a PR.

**Comment by SchSeba** [comment]
I do not think there is a way to automate this as we don't have github actions here maybe something in the openshift-ci can do it but again, I'm not sure.

I would like to have at least an entry in the d/s Makefile where we have a version that we can update with a `bump bundle` or something like that.
