### ISSUE TITLE
No SetVfGuid()

### ISSUE THREAD

**Issue by SakaZhang** [openshift/sriov-network-operator#941]
Here is my pods:
```bash
root@node1:~# kubectl  get pods -n sriov-network-operator -o wide | grep node19
sriov-device-plugin-b4555                 1/1     Running   0             4m4s   10.200.1.19      node19   <none>           <none>
sriov-network-config-daemon-8psqw         1/1     Running   0             4m4s   10.200.1.19      node19   <none>           <none>
```
And i deployed sriove-network-operator follow the https://github.com/openshift/sriov-network-operator/blob/master/doc/quickstart.md 
Now in my k8s cluster, some nodes got the random guid setted, but the most nodes got 
```bash
vf 5     link/infiniband 00:00:0c:79:fe:80:00:00:00:00:00:00:a0:88:c2:03:00:d6:49:a2 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff, spoof checking off, NODE_GUID 00:00:00:00:00:00:00:00, PORT_GUID 00:00:00:00:00:00:00:00, link-state enable, trust off, query_rss off
```
And no logs show like `log.Log.Info("SetVfGUID()","vf", vfAddr)` 
I wonder why sriov-network-operator didn't set ib node_guid and when the guids are setted?

**Comment by SchSeba** [comment]
Hi @SakaZhang please open an issue to the u/s repo.

This repo is only a fork from https://github.com/k8snetworkplumbingwg/sriov-network-operator/

/close
