### ISSUE TITLE
sriov-network-operator is not up by error "unable to create index fieldn version \"sriovnetwork.openshift.io/v1\""}"

### ISSUE THREAD

**Issue by LiuCarl** [openshift/sriov-network-operator#956]
i'm trying the sriov-network-operator on the k8s 1.27.6
i used the kube-ovn as the cni for the k8s.

[root@rocky-k8s-237 system]# kubectl get pods -n sriov-network-operator
NAME                                      READY   STATUS             RESTARTS         AGE
sriov-network-operator-66f984969f-j9rzw   0/1     CrashLoopBackOff   15 (3m36s ago)   34m

pod logs as below:
2024-07-08T03:03:53.553462294Z	ERROR	setup	runtime/proc.go:271	unable to create index fieldn version \"sriovnetwork.openshift.io/v1\""}

question:  does the sriov-network-operator supports kube-ovn as the cni? or what shall i added to fix it?

**Comment by zeeke** [comment]
Hi @LiuCarl! This repository is for openshift changes only.
Please, open an issue on the upstream repo https://github.com/k8snetworkplumbingwg/sriov-network-operator and discuss the issue with the rest of the community.

**Comment by LiuCarl** [comment]
ok

**Comment by SchSeba** [comment]
thanks!

closing this one

/close
