### ISSUE TITLE
which repo to use

### ISSUE THREAD

**Issue by jeffreyyjp** [openshift/sriov-network-operator#993]
Hello, I want to know the difference between this repo and https://github.com/k8snetworkplumbingwg/sriov-network-operator.
If I use k8s cluster(not openshift), which one should I choose.

**Comment by zeeke** [comment]
hi @jeffreyyjp , https://github.com/k8snetworkplumbingwg/sriov-network-operator repository is the upstream one, where all the feature and fix are implemented in first place. It is maintainer by community members.

This repository (`openshift/*`) is a fork (though not technically) where commits are pulled from upstream and released through OpesShift. e.g. Here, you can find a branch for each OpenShift version.

If you have any problem, I suggest you to open an issue in the upstream repo.

**Comment by jeffreyyjp** [comment]
@zeeke Thank you for providing this detail.
